// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    StandardWrapper: typeof import('./src/components/StandardWrapper/index.vue')['default']
    TreeNode: typeof import('./src/components/ElTreeV2/TreeNode.vue')['default']
    Versions: typeof import('./src/components/Versions.vue')['default']
    VirtualScroll: typeof import('./src/components/VirtualScroll/src/VirtualScroll.vue')['default']
    VisitAnalysisStandard: typeof import('./src/components/StandardWrapper/VisitAnalysisStandard.vue')['default']
  }
}
